#!/bin/bash
echo ""
echo "🔥==============================🔥"
echo "     PORTE DU FEU — ÉPREUVE 1"
echo "🔥==============================🔥"
echo ""
echo "Le feu teste ta rapidité et ton instinct."
echo "Réponds par 'Vrai' ou 'Faux' à chaque affirmation."
echo "Tape OUT si tu veux abandonner la flamme..."
echo ""
